CREATE TABLE "usuario" (
  "cedula" varchar(20) PRIMARY KEY,
  "nombre" varchar(200),
  "telefono" varchar(20),
  "correo" varchar(100) UNIQUE,
  "direccion" varchar(200)
);

CREATE TABLE "lugar" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100),
  "tipo" varchar(100)
);

CREATE TABLE "turno" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cedula" varchar(20),
  "tipo_lugar" varchar(50),
  "id_lugar" int NULL,
  "posicion" int,
  "fecha" TIMESTAMP,
  "estado" varchar(20)
);

COMMENT ON TABLE "turno" IS 'estado: pendiente | atendiendo | finalizado';

ALTER TABLE "turno"
ADD FOREIGN KEY ("cedula") REFERENCES "usuario" ("cedula");

ALTER TABLE "turno"
ADD FOREIGN KEY ("id_lugar") REFERENCES "lugar" ("id");

--------------------------------------------------
-- INSERTS USUARIO
--------------------------------------------------

INSERT INTO usuario VALUES
('1001', 'Juan Perez', '3001234567', 'juan@mail.com', 'Calle 1'),
('1002', 'Maria Gomez', '3002345678', 'maria@mail.com', 'Calle 2'),
('1003', 'Carlos Ruiz', '3003456789', 'carlos@mail.com', 'Calle 3'),
('1004', 'Ana Torres', '3004567890', 'ana@mail.com', 'Calle 4'),
('1005', 'Luis Martinez', '3005678901', 'luis@mail.com', 'Calle 5');

--------------------------------------------------
-- INSERTS LUGAR
--------------------------------------------------

INSERT INTO lugar (nombre, tipo) VALUES
('Consultorio 1', 'consulta'),
('Consultorio 2', 'consulta'),
('Farmacia', 'medicamentos'),
('Caja 1', 'administrativo'),
('Laboratorio 1', 'laboratorio');

--------------------------------------------------
-- INSERTS TURNO
--------------------------------------------------

INSERT INTO turno (cedula, tipo_lugar, posicion, fecha, estado) VALUES
('1001', 'consulta', 1, NOW(), 'pendiente'),
('1002', 'consulta', 2, NOW(), 'pendiente'),
('1003', 'medicamentos', 1, NOW(), 'atendiendo'),
('1004', 'administrativo', 1, NOW(), 'finalizado'),
('1005', 'consulta', 3, NOW(), 'pendiente');