CREATE TABLE "usuario" (
  "cedula" varchar(20) PRIMARY KEY,
  "nombre" varchar(200),
  "telefono" varchar(20),
  "correo" varchar(100) UNIQUE,
  "direccion" varchar(200)
);

CREATE TABLE "lugar" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100),
  "tipo" varchar(100)
);

CREATE TABLE "turno" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cedula" varchar(20),
  "id_lugar" int,
  "posicion" int,
  "fecha" datetime,
  "estado" varchar(20)
);

COMMENT ON TABLE "turno" IS 'estado: pendiente | atendiendo | finalizado';

ALTER TABLE "turno" ADD FOREIGN KEY ("cedula") REFERENCES "usuario" ("cedula") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "turno" ADD FOREIGN KEY ("id_lugar") REFERENCES "lugar" ("id") DEFERRABLE INITIALLY IMMEDIATE;
